### ISSUE TITLE
Invalid git command issued with multiple files

### ISSUE THREAD

**Issue by OscarAblinger** [github-actions-x/commit#12]
If specifying multiple files to commit, the resulting git command seems to be invalid.

The following configuration:

```yaml
jobs:
  build-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Add new commit
      uses: github-actions-x/commit@v2.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: yaml2markdown.sh"
        files: README.md dist/projects_by_sdg.json
```

results in the following command: (if I read the error correctly)

```sh
/usr/bin/git add -A 'README.md dist/projects_by_sdg.json'
```

Correctly it should be:
```sh
/usr/bin/git add -A 'README.md' 'dist/projects_by_sdg.json'
```

Am I just using the `files` parameter wrong or is this actually a bug?
In the README the parameters seems to be the same: `files: a.txt b.txt c.txt dirA/ dirB/ dirC/a.txt`

[Full config](https://github.com/awesome-global-contributions/awesome-global-contributions/blob/c21d8f7284943d9b00607a0624e43e2dd666921c/.github/workflows/main.yml)
Full github error:

```
login AblingerOscar
password ***
machine api.github.com
login AblingerOscar
password ***


Traceback (most recent call last):
  File "/entrypoint.py", line 52, in <module>
    run()
  File "/entrypoint.py", line 47, in run
    debug(git(add_args))
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 233, in run
    return p.run()
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 194, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 247, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | /usr/bin/git add -A 'README.md dist/projects_by_sdg.json'
Stderr:       | fatal: pathspec 'README.md dist/projects_by_sdg.json' did not match any files
##[error]Docker run failed with exit code 1
```

**Comment by ThePieBandit** [comment]
I have the same problem. From what I can tell, It's something occurring when the env variables are passed to the docker container, not the python script itself. I tried just running the python file locally after setting my env file as `INPUT_FILES="foo.txt barr.png"` and exporting it, and my output was `##[debug]add -A foo.txt barr.png`

test file:

```#!/usr/bin/env python3

from plumbum import local
import os

def debug(message: str):
    print(f'##[debug]{message}')


def run():
    files = local.env.get('INPUT_FILES', '')
    echo = local['echo']
    add_args = ['add']
    add_args.append('-A')
    if files:
        add_args.append(files)
    debug(echo(add_args))

if __name__ == '__main__':
    run()```

**Comment by perseus-me** [comment]
Thanks for report, I fix that.
