### ISSUE TITLE
Run on a tag fails

### ISSUE THREAD

**Issue by paskal** [github-actions-x/commit#19]
Here is the code I'm using:

```yaml
    - name: commit kernel-specific library
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.BPFINK_COMMIT_TOKEN }}
        commit-message: 'bump kernel-specific libraries'
        rebase: true
        files: pkg/ebpf
        name: bpfink automatic commit
        email: paskal.07@gmail.com
```

[Here is the output](https://github.com/bookingcom/bpfink/runs/788182569):

```
login ramyahasini
password ***
machine api.github.com
login ramyahasini
password ***


nothing to commit, working tree clean

Traceback (most recent call last):
  File "/entrypoint.py", line 53, in <module>
    run()
  File "/entrypoint.py", line 50, in run
    debug(git(['push', '--follow-tags', '--set-upstream', 'origin', branch]))
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 232, in run
    return p.run()
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /usr/bin/git push --follow-tags --set-upstream origin 0.6.36
Stderr:       | error: src refspec 0.6.36 matches more than one
              | error: failed to push some refs to 'https://github.com/bookingcom/bpfink'
```

This is a run on a [tag release](https://github.com/bookingcom/bpfink/releases/tag/0.6.36) created in GitHub UI.

**Comment by nerdyscout** [comment]
i think i have been running into the same issue. disabling rebase "solved" it for me.

**Comment by paskal** [comment]
Closing this from my side: filed in 2020, and I no longer use this action.
