### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by cakeinpanic** [github-actions-x/commit#20]
Hi! 

Have some problems with running the action, take a look please:
```
Traceback (most recent call last):
  File "/entrypoint.py", line 53, in <module>
    run()
  File "/entrypoint.py", line 47, in run
    debug(git(['checkout', '-B', branch]))
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 232, in run
    return p.run()
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | /usr/bin/git checkout -B master
Stderr:       | fatal: not a git repository (or any parent up to mount point /github)
              | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
configuration:
```
 push-build:
    needs: build-test # another job
    if: needs.build-test.outputs.LIB_DIFF
    runs-on: ubuntu-16.04
    steps:
    - name: "archive lib when diff"
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'build action'
        files: lib
        name: Build action bot
        email: buildaction@bot.bot

```

**Comment by cakeinpanic** [comment]
It may be connected to the fact. I have added another remote on my local machine. But I have removed it, re-initialized repo, but it did not help :(
