### ISSUE TITLE
Does not work well with matrix

### ISSUE THREAD

**Issue by moltar** [github-actions-x/commit#5]
When using matrix, the first matrix variation works.

But the second fails.

I am guessing that is because there needs to be a `git pull -r` to merge the changes of the first push.

```
Traceback (most recent call last):
  File "/entrypoint.py", line 44, in <module>
    run()
  File "/entrypoint.py", line 41, in run
    debug(git(['push', '--follow-tags', '--set-upstream', 'origin', branch]))
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 103, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 232, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/bin/git', 'push', '--follow-tags', '--set-upstream', 'origin', 'master']
Exit code: 1
Stderr:  | To https://github.com/moltar/typescript-runtime-type-benchmarks
         |  ! [rejected]        master -> master (fetch first)
         | error: failed to push some refs to 'https://github.com/moltar/typescript-runtime-type-benchmarks'
         | hint: Updates were rejected because the remote contains work that you do
         | hint: not have locally. This is usually caused by another repository pushing
         | hint: to the same ref. You may want to first integrate the remote changes
         | hint: (e.g., 'git pull ...') before pushing again.
         | hint: See the 'Note about fast-forwards' in 'git push --help' for details.
##[error]Docker run failed with exit code 1
```

**Comment by moltar** [comment]
This can also be fixed by simply adding the following step before:

```
      - run: git pull --rebase --autostash origin master
```

See:

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/.github/workflows/nodejs.yml

So maybe no changes needed internally, but maybe it is worth documenting this?

**Comment by perseus-me** [comment]
I add option `rebase` to workflow. See README.

**Comment by moltar** [comment]
```
Current runner version: '2.158.0'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'actions/setup-node@v1'
Download action repository 'github-actions-x/commit@v2.1'
##[warning]Failed to download action 'https://api.github.com/repos/github-actions-x/commit/tarball/v2.1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 18.084 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/github-actions-x/commit/tarball/v2.1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 17.229 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).
```

Is the `v2.1` published?

Thanks

**Comment by moltar** [comment]
Oh I see, the `v` is missing on the published tag

**Comment by perseus-me** [comment]
Yes, my bad. Fix it.
